# NUMPY ASSSIGNMENT

In [146]:
import numpy as np

In [147]:
#1.Create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [148]:
arr_n = np.array([1, 7, 13, 105])
print(arr_n)
print(f"Total no of Bytes occupied = {arr_n.nbytes}")

[  1   7  13 105]
Total no of Bytes occupied = 32


In [149]:
#2.Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [150]:
arr_1 = np.array([10, 20 , 35, 49, 97, 108])
arr_2 = np.array([11, 22, 33, 44, 97, 108])
print(arr_1)
print(arr_2)
print(arr_1 > arr_2)
print(arr_1 < arr_2)
print(arr_1 >= arr_2)
print(arr_1 <= arr_2)

[ 10  20  35  49  97 108]
[ 11  22  33  44  97 108]
[False False  True  True False False]
[ True  True False False False False]
[False False  True  True  True  True]
[ True  True False False  True  True]


In [151]:
#3.Create an array of 10 zeros, 10 ones, 10 fives, 10 tens, 10 twentys and 10 fiftys.

In [152]:
arr_0 = np.zeros(10)
arr_1 = np.ones(10)
arr_5 = np.ones(10)*5
arr_10 = np.ones(10)*10
arr_20 = np.ones(10)*20
arr_50 = np.ones(10)*50
print (f"Array of 10 zeros = {arr_0}")
print (f"Array of 10 ones = {arr_1}")
print (f"Array of 10 fives = {arr_5}")
print (f"Array of 10 fives = {arr_10}")
print (f"Array of 10 fives = {arr_20}")
print (f"Array of 10 fives = {arr_50}")
# print (f"Array of 10 fives = {arr_1 * 5}")
# print (f"Array of 10 tens = {arr_1 * 10}")
# print (f"Array of 10 twentys = {arr_1 * 20}")
# print (f"Array of 10 fifties = {arr_1 * 50}")

Array of 10 zeros = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives = [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
Array of 10 fives = [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
Array of 10 fives = [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
Array of 10 fives = [50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [153]:
#4.Create an array of integers from 30 to 70.

In [154]:
arr_n = np.arange(30,71)
print(f"Array from integers 30 to 71 = {arr_n}")

Array from integers 30 to 71 = [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [155]:
#5.Create an array of integers from 50 to 95.

In [156]:
arr_n = np.arange(50,96)
print(f"Array from integers 50 to 96 = {arr_n}")

Array from integers 50 to 96 = [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [157]:
#6.Create an array of all even integers from 20 to 80.

In [158]:
arr_n = np.arange(20,81,2)
print(f"Array of even integers from 20 to 80 = {arr_n}")

Array of even integers from 20 to 80 = [20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [159]:
#7.Create an array of all odd integers from 20 to 80.

In [160]:
arr_n = np.arange(21,81,2)
print(f"Array of odd integers from 20 to 80 = {arr_n}")

Array of odd integers from 20 to 80 = [21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [161]:
#8.Generate an array of 15 random numbers from 10 to 40.

In [162]:
arr_n = np.random.randint(10, 40, size=15)
print(f"Array of 15 random numbers from 10 to 40 = {arr_n}")

Array of 15 random numbers from 10 to 40 = [10 16 11 23 37 29 28 35 21 10 11 12 21 32 23]


In [163]:
#9.Generate an array of 10 random numbers from 30 to 50.

In [164]:
arr_n = np.random.randint(30, 50, size=10)
print(f"Array of 10 random numbers from 30 to 50 = {arr_n}")

Array of 10 random numbers from 30 to 50 = [40 31 48 46 44 49 40 38 42 38]


In [165]:
#10.Generate an array of 20 random numbers from 50 to 90.

In [166]:
arr_n = np.random.randint(50, 90, size=20)
print(f"Array of 20 random numbers from 50 to 90 = {arr_n}")

Array of 20 random numbers from 50 to 90 = [51 77 61 66 84 59 58 59 84 70 70 63 89 62 76 81 51 70 72 54]


In [167]:
#11. Create any two arrays & perform various mathematical operations. i.e. Addition, Substraction, Multiplication, Division.

In [168]:
arr_1 = np.array([7, 18, 45, 91, 33])
arr_2 = np.array([8, 12, 36, 1, 69])
print(f"Addition of two arrays = {arr_1 + arr_2}")
print(f"Substraction of two arrays = {arr_1 + arr_2}")
print(f"Multiplication of two arrays = {arr_1 * arr_2}")
print(f"Division of two arrays = {arr_1 / arr_2}")

Addition of two arrays = [ 15  30  81  92 102]
Substraction of two arrays = [ 15  30  81  92 102]
Multiplication of two arrays = [  56  216 1620   91 2277]
Division of two arrays = [ 0.875       1.5         1.25       91.          0.47826087]


In [169]:
#12.create a 3x4 matrix filled with values from 10 to 21.

In [170]:
n_arr = np.arange(10,22)
n_arr = n_arr.reshape([3,4])
print(n_arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [171]:
#13.Create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [172]:
# arr_m = np.array([1,0,0,0,1,0,0,0,1])
# arr_m = arr_m.reshape([3,3])
# print(arr_m)
identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [173]:
#14.Find the number of rows and columns in a given matrix.

In [174]:
mat_arr = np.array([[11, 22, 33],
                    [44, 55, 66],
                    [77, 88, 99]])

rows,cols = mat_arr.shape
print("Number of rows:", rows)
print("Number of columns:", cols)

Number of rows: 3
Number of columns: 3


In [175]:
#15.Create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [176]:
arr_m = np.zeros((5, 5))
diag_val = np.array([1, 2, 3, 4, 5])

# Replace the diagonal elements with the specified values
np.fill_diagonal(arr_m, diag_val)
print(arr_m)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [177]:
#16.Create a 3x3x3 array filled with arbitrary values.

In [178]:
arr_m = np.random.randint(1,25,size=(3, 3, 3))
print(f"Random array of 3x3x3 = {arr_m}")

Random array of 3x3x3 = [[[18 20  3]
  [23  8 12]
  [ 5 11 16]]

 [[ 7  5 18]
  [17 17 16]
  [14  4 20]]

 [[ 6 13  6]
  [ 2 12 21]
  [10  3 21]]]


In [179]:
#17.Create a 2x3x4 array filled with arbitrary values.

In [180]:
arr_m1 = np.random.randint(1,25,size=(2, 3, 4))
print(f"Random array of 2x3x4 = {arr_m1}")

Random array of 2x3x4 = [[[20  6  5 19]
  [ 9 19 24 21]
  [ 3  4 22 17]]

 [[ 6 21  4 23]
  [ 2  7  5  1]
  [ 9  2 18 21]]]


In [181]:
#18.Convert a list of numeric values into a one-dimensional NumPy array.

In [182]:
l1 = [11,22,33,44,55,66,77,88,99]
print(f"Type = {type(l1)}")
n_arr = np.array(l1)
print(f"Type = {type(n_arr)}")

Type = <class 'list'>
Type = <class 'numpy.ndarray'>


In [183]:
#19.Create a 3x3 matrix with values ranging from 2 to 10.

In [184]:
arr_mat = np.arange(2,11).reshape(3, 3)
# arr_mat1 = np.random.randint(2,11,size=(3, 3))
print(f"array of 3x3 from values 2 to 10 = {arr_mat}")

array of 3x3 from values 2 to 10 = [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [185]:
#20.Create an array with values ranging from 12 to 38.

In [186]:
arr_n = np.arange(12,39)
print(f"Array from integers 12 to 38 = {arr_n}")

Array from integers 12 to 38 = [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [187]:
#21.Reverse an array (the first element becomes the last).

In [188]:
arr_p = np.array([12,13,14,15,16,17,18,19,20])
rev_arr_p = np.flip(arr_p)
print(rev_arr_p)

[20 19 18 17 16 15 14 13 12]


In [189]:
#22.Convert an data type into to a floating type.

In [190]:
int_arr = np.array([11,22,33,44,55,66,77])
float_arr = int_arr.astype(float)
print("Integer array:", int_arr)
print("Float array:", float_arr)
print("Data types:")
print("Integer array:", int_arr.dtype)
print("Float array:", float_arr.dtype)

Integer array: [11 22 33 44 55 66 77]
Float array: [11. 22. 33. 44. 55. 66. 77.]
Data types:
Integer array: int64
Float array: float64


In [191]:
#23.Convert a list into array.

In [192]:
l2 = [21,22,33,34,55,56,77,78,99,100]
print(f"Type = {type(l2)}")
n_arr = np.array(l2)
print(f"Type = {type(n_arr)}")

Type = <class 'list'>
Type = <class 'numpy.ndarray'>


In [193]:
#24.Get the element-wise remainder of an array of division.

In [194]:
arr_1 = np.array([10, 20, 30, 40, 50])
arr_2 = np.array([3, 4, 5, 6, 7])
rem = arr_1 % arr_2
print(f"Element-wise remainder = {rem}")

Element-wise remainder = [1 0 0 4 1]


In [195]:
#25.Get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [196]:
arr_div_3 = np.arange(21, 51, 3)
print(f"Array divisible by 3 = {arr_div_3}")
print(f"Element-wise remainder = {arr_div_3 % 3}")

Array divisible by 3 = [21 24 27 30 33 36 39 42 45 48]
Element-wise remainder = [0 0 0 0 0 0 0 0 0 0]
